fix: bump jre version
run-ci

#20 46.73 [INFO] ERROR in closure-compiler: Error: A JNI error has occurred, please check your installation and try again
#20 46.73 [INFO] Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
#20 46.73 [INFO] 	at java.lang.ClassLoader.defineClass1(Native Method)
#20 46.73 [INFO] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
#20 46.73 [INFO] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
#20 46.73 [INFO] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
#20 46.73 [INFO] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
#20 46.73 [INFO] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
#20 46.73 [INFO] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
#20 46.73 [INFO] 	at java.security.AccessController.doPrivileged(Native Method)
#20 46.73 [INFO] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
#20 46.73 [INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
#20 46.73 [INFO] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
#20 46.73 [INFO] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
#20 46.73 [INFO] 	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:621)
#20 46.76 [INFO] ------------------------------------------------------------------------
#20 46.76 [INFO] Reactor Summary for guacamole-client 1.5.5:
#20 46.76 [INFO]
#20 46.77 [INFO] guacamole-client ................................... SUCCESS [  7.015 s]
#20 46.77 [INFO] guacamole-common ................................... SUCCESS [  5.647 s]
#20 46.77 [INFO] guacamole-ext ...................................... SUCCESS [  4.559 s]
#20 46.77 [INFO] guacamole-common-js ................................ SUCCESS [ 10.655 s]
#20 46.77 [INFO] guacamole .......................................... FAILURE [ 17.577 s]
#20 46.77 [INFO] extensions ......................................... SKIPPED
#20 46.77 [INFO] guacamole-auth-duo ................................. SKIPPED
#20 46.77 [INFO] guacamole-auth-header .............................. SKIPPED
#20 46.77 [INFO] guacamole-auth-jdbc ................................ SKIPPED
#20 46.77 [INFO] guacamole-auth-jdbc-base ........................... SKIPPED
#20 46.77 [INFO] guacamole-auth-jdbc-mysql .......................... SKIPPED
#20 46.77 [INFO] guacamole-auth-jdbc-postgresql ..................... SKIPPED
#20 46.77 [INFO] guacamole-auth-jdbc-sqlserver ...................... SKIPPED
#20 46.77 [INFO] guacamole-auth-jdbc-dist ........................... SKIPPED
#20 46.77 [INFO] guacamole-auth-json ................................ SKIPPED
#20 46.77 [INFO] guacamole-auth-ldap ................................ SKIPPED
#20 46.77 [INFO] guacamole-auth-quickconnect ........................ SKIPPED
#20 46.77 [INFO] guacamole-auth-sso ................................. SKIPPED
#20 46.77 [INFO] guacamole-auth-sso-base ............................ SKIPPED
#20 46.77 [INFO] guacamole-auth-sso-cas ............................. SKIPPED
#20 46.77 [INFO] guacamole-auth-sso-openid .......................... SKIPPED
#20 46.77 [INFO] guacamole-auth-sso-saml ............................ SKIPPED
#20 46.77 [INFO] guacamole-auth-sso-dist ............................ SKIPPED
#20 46.77 [INFO] guacamole-auth-totp ................................ SKIPPED
#20 46.77 [INFO] guacamole-history-recording-storage ................ SKIPPED
#20 46.77 [INFO] guacamole-vault .................................... SKIPPED
#20 46.77 [INFO] guacamole-vault-base ............................... SKIPPED
#20 46.77 [INFO] guacamole-vault-ksm ................................ SKIPPED
#20 46.77 [INFO] guacamole-vault-dist ............................... SKIPPED
#20 46.77 [INFO] guacamole-example .................................. SKIPPED
#20 46.77 [INFO] guacamole-playback-example ......................... SKIPPED
#20 46.77 [INFO] ------------------------------------------------------------------------
#20 46.77 [INFO] BUILD FAILURE
#20 46.77 [INFO] ------------------------------------------------------------------------
#20 46.77 [INFO] Total time:  45.702 s
#20 46.77 [INFO] Finished at: 2025-02-01T01:50:36Z
#20 46.77 [INFO] ------------------------------------------------------------------------
#20 46.77 [ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.3:npm (npm-build) on project guacamole: Failed to run task: 'npm run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
#20 46.77 [ERROR]
#20 46.77 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
#20 46.77 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
#20 46.77 [ERROR]
#20 46.77 [ERROR] For more information about the errors and possible solutions, please read the following articles:
#20 46.77 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
#20 46.77 [ERROR]
#20 46.77 [ERROR] After correcting the problems, you can resume the build with the command
#20 46.77 [ERROR]   mvn <args> -rf :guacamole
#20 ERROR: process "/bin/sh -c /opt/guacamole/bin/build-guacamole.sh \"$BUILD_DIR\" /opt/guacamole" did not complete successfully: exit code: 1
------
 > [builder 11/11] RUN /opt/guacamole/bin/build-guacamole.sh "/tmp/guacamole-docker-BUILD" /opt/guacamole:
Error: ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.11.3:npm (npm-build) on project guacamole: Failed to run task: 'npm run build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
Error: ERROR]
Error: ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
Error: ERROR] Re-run Maven using the -X switch to enable full debug logging.
Error: ERROR]
Error: ERROR] For more information about the errors and possible solutions, please read the following articles:
Error: ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
Error: ERROR]
Error: ERROR] After correcting the problems, you can resume the build with the command
Error: ERROR]   mvn <args> -rf :guacamole
------